# Generated by Django 3.2.9 on 2022-04-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220413_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='SRN',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='college_address',
            new_name='Semester',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.AddField(
            model_name='profile',
            name='Campus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Course',
            field=models.CharField(blank=True, help_text='Eg. - BBA, B-tech,etc', max_length=100, null=True),
        ),
    ]
