# Generated by Django 3.2.9 on 2022-04-13 15:55

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_slug', models.SlugField(auto_created=True, max_length=200, unique=True)),
                ('category_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_slug', models.SlugField(auto_created=True, max_length=200, unique=True)),
                ('product_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('desc', ckeditor.fields.RichTextField()),
                ('specification', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('product_cover_image', models.ImageField(upload_to='products_img', verbose_name='Cover Image')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products_img', verbose_name='2nd Image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products_img', verbose_name='3rd Image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products_img', verbose_name='4th Image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products_img', verbose_name='5th Image')),
                ('price', models.DecimalField(decimal_places=2, help_text='MRP', max_digits=5)),
                ('featured_product', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
