# Generated by Django 3.2.9 on 2022-04-13 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='No Subject', max_length=2000)),
                ('text', models.TextField()),
                ('sent_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='try to add .png or .jpg files for easier accomoadation of images', null=True, upload_to='layout_pics')),
                ('active', models.BooleanField(default=False, help_text='to make it as an active set of images')),
            ],
        ),
    ]
